### ISSUE TITLE
PyPI

### ISSUE THREAD

**Issue by rossant** [pombredanne/pipo#1]
Hi @pombredanne 

I'm making [a little script named *pipo*](https://github.com/rossant/pipo) to simplify the management of Python packages using setuptools, PyPI, etc. I see that you had had a similar idea a few years ago and reserved that same name on PyPI, but you never ended up doing it! I was wondering if you'd accept to remove or transfer the PyPI name to me?

Many thanks!
Cyrille

**Comment by pombredanne** [comment]
@rossant with pleasure
Actually this has eventually morphed in this https://github.com/nexB/scancode-toolkit/blob/develop/etc/configure.py and the top level corresponding scripts. And I use it as a replacement for buildout and to deal with vendored packages.
Tell me what I shall do to hand over the name on Pypi!

**Comment by pombredanne** [comment]
@rossant This is my first issue for a project without __any__ code ! :D

**Comment by pombredanne** [comment]
@rossant and in contrast with some npm folks, pythonista are gentle people http://www.businessinsider.com/npm-left-pad-controversy-explained-2016-3

**Comment by rossant** [comment]
@pombredanne so I think you can login to PyPI, go to [the project's page](https://pypi.python.org/pypi?%3Aaction=pkg_edit&name=pipo), and click on **Do NOT use this button** at the bottom (ha!). Hopefully it will work and it won't break the Internet like left-pad did :p

**Comment by pombredanne** [comment]
```
You are about to remove the project all information about and all releases of project pipo. from PyPI
This action cannot be undone!

Consider that removing this may break people's system builds.
Are you sure?
```
OK. Done!

**Comment by pombredanne** [comment]
@rossant The name is yours!

**Comment by rossant** [comment]
```
cyrille:~/git/pipo$ pipo register
Registering pipo to https://pypi.python.org/pypi
Server response (200): OK
cyrille:~/git/pipo$ pipo release
Uploading distributions to https://pypi.python.org/pypi
Uploading pipo-0.1.0-py3-none-any.whl
Uploading pipo-0.1.0.tar.gz
```

Thanks!!

**Comment by pombredanne** [comment]
@rossant `cyrille:~/git/pipo$ pipo register` :+1:  : registering pipo with pipo has a certain recursive self-bootstrapping elegance ring to it

**Comment by pombredanne** [comment]
@rossant you may not get rid of me so easily... I might start using pipo :P
